# fly.toml app configuration file generated for rough-wave-2704 on 2023-08-06T10:23:50+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rough-wave-2704"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
